### ISSUE TITLE
bug:  Fatal error: appId is empty

### ISSUE THREAD

**Issue by macsupport** [Cap-go/capacitor-updater#275]
### Capacitor Version

```
 @capacitor/cli: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/ios: 5.4.1
```

### Plugin Version

```
  @capgo/cli: 3.14.2
   @capgo/capacitor-updater: 5.3.9
```

### context(s)

```md

AutoMode: false

```

### Current Behavior

Loading network plugin
✨  Capacitor-updater: semaphoreUp
✨  Capacitor-updater: init for device BDA87D5A-6803-4E25-A9E9-126891F3BE59
✨  Capacitor-updater: semaphoreWait 0
✨  Capacitor-updater: version native 3.1.0
✨  Capacitor-updater: appId is empty
CapgoCapacitorUpdater/CapacitorUpdaterPlugin.swift:69: Fatal error: appId is empty

### Other Technical Details

Crashes App on startup before splash screen shows
`npm --version` output:
8.19.2
`node --version` output:
19.0.0
`pod --version` output (iOS issues only):
1.13.0

**Comment by khamaileon** [comment]
I just updated from 5.2.35 to 5.3.9 and I have the same problem.

```
Process: app.example, PID: 8684
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.example/app.example.MainActivity}: java.lang.RuntimeException: appId is required
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.RuntimeException: appId is required
	at ee.forgr.capacitor_updater.CapacitorUpdaterPlugin.load(CapacitorUpdaterPlugin.java:168)
	at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:115)
	at com.getcapacitor.PluginHandle.load(PluginHandle.java:105)
	at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
	at com.getcapacitor.Bridge.registerPlugin(Bridge.java:644)
	at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:600)
	at com.getcapacitor.Bridge.<init>(Bridge.java:215)
	at com.getcapacitor.Bridge.<init>(Unknown Source:0)
	at com.getcapacitor.Bridge$Builder.create(Bridge.java:1519)
	at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:42)
	at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:36)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:226) 
	at android.os.Looper.loop(Looper.java:313) 
	at android.app.ActivityThread.main(ActivityThread.java:8762) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 
```

**Comment by kinggolf** [comment]
Exact same issue here when updating from 5.2.35 to 5.3.10.

**Comment by G3z** [comment]
Android fails to read appId properly from `config.getString("appId", ""); `

this check has been introduced in 5.3.3 (so 5.3.2 should work)
https://github.com/Cap-go/capacitor-updater/blob/92345393b917ab73ebbd4363ead0cebe3d9b6ada/android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java#L162-L169

**Comment by yakovyarmo** [comment]
same issue

**Comment by kinggolf** [comment]
5.3.11 is working on Android. Thank you Capgo team!

**Comment by macsupport** [comment]
Sadly, same error in 5.3.11 in iOS. Crashes the App

**Comment by kinggolf** [comment]
@macsupport 5.3.11 is working for me on iOS build. Android OK & iOS OK.

**Comment by riderx** [comment]
@macsupport can you check to do a cap sync ? sometimes that the missing part

**Comment by Oidlichtnwoada** [comment]
same issue here ...

**Comment by Oidlichtnwoada** [comment]
It fails on Android and iOS and prevents the app from starting ... with the exact same reason described above ...

**Comment by macsupport** [comment]
Just installed the newest version, 5.3.20. Same issue for me. ( I always do a cap sync)

`Capacitor-updater: appId is empty
CapgoCapacitorUpdater/CapacitorUpdaterPlugin.swift:72: Fatal error: appId is empty`

**Comment by kinggolf** [comment]
5.3.20 is working for me on both iOS and Android. This feels similar to previous issues with Ionic/Capacitor splash screen updates not working immediately. It is something like the Xcode is cacheing values for some time, but eventually starts working. But not sure...

**Comment by riderx** [comment]
@macsupport @Oidlichtnwoada are you using capacitor 5?
I added this check because the updater was crashing otherwise at runtime with app using v5 with capacitor v4

**Comment by Oidlichtnwoada** [comment]
@riderx Yes I am using Capacitor 5.5.0

**Comment by macsupport** [comment]
Yes, 5.5

**Comment by riderx** [comment]
If any of you are available to call, I would like to live debug it.

**Comment by joshstrange** [comment]
I'm using `@capacitor/core@5.4.2` and `@capgo/capacitor-updater@5.3.20` and it's working for Android/iOS locally (or rather the builds complete and the app launches in the simulator/emulator). I'm about to kick off GH Action builds to build and push to the stores. If I don't report back you can assume that worked for me.

**Comment by macsupport** [comment]
Sadly, same issue in 5.3.26

**Comment by riderx** [comment]
@macsupport are you available for a call i need to look with you

**Comment by Oidlichtnwoada** [comment]
@riderx 
I think the error is here:

  final CapConfig config = CapConfig.loadDefault(this.getActivity());
  this.implementation.appId = config.getString("appId", "");
  this.implementation.appId =
    this.getConfig().getString("appId", this.implementation.appId);
  if (!"".equals(implementation.appId)) {
    Log.i(CapacitorUpdater.TAG, "appId: " + implementation.appId);
    throw new RuntimeException("appId is required");
  }
  
 I have no idea what CapConfig is doing, but I have not set appId in the plugin options as it can be queried from the app, 
 the error is thrown when the appId is not equal to the empty string, should not it be the other way around ...

**Comment by riderx** [comment]
The cap config is the global config not the plugin config.
So the plugin try to read the capacitor config file and find the appID in it.
If you have a capacitor config with appID at the root it should work.
And it works for many apps, there one few who fail and that why the check is made.
I got some users complaining capgo wasn’t working for them and the issue was appID missing so now the plugin explicitly crash if he cannot find it

**Comment by Oidlichtnwoada** [comment]
<img width="424" alt="image" src="https://github.com/Cap-go/capacitor-updater/assets/42490916/4e98a08e-23ad-4ef9-a6e4-8a390b8febe3">
@riderx 
Thanks, this was the issue ...
However I do not want to add appId, since we are using the same capacitor config for multiple apps with different Ids, you could just read out the id with https://www.npmjs.com/package/@capacitor/app which is the easiest and safest way, as this is the id used by the running app, not the id that was written to the config when the app was first generated and was later not changed ... the appid is just needed in the config for generating the first cap project and its used for nothing else ...

**Comment by riderx** [comment]
Hello @Oidlichtnwoada, for your case it works I agree, this has been done because not everyone have the same appId in IOS and Android in the native.
Capgo was not working for them ( me included )
What I can do is to search for appId in the plugin, then in the root of capacitor config and then if not found default to the native one, i beleive that will work for all.

**Comment by riderx** [comment]
I just pushed the change who read first the native bundle, we should now be good on that one !
Thanks all for your feedback, i'm really sorry that blocked you so long.
I leave it open until you confirm this fix:
https://github.com/Cap-go/capacitor-updater/tree/5.3.28

**Comment by Oidlichtnwoada** [comment]
Can you make a beta release in npm, such that we can more easily test it?

**Comment by riderx** [comment]
@Oidlichtnwoada this is released in production already with `5.3.29`

**Comment by Oidlichtnwoada** [comment]
@riderx everything works now ... thanks ....
